### ISSUE TITLE
Remove page title from categories

### ISSUE THREAD

**Issue by briggySmalls** [jerome-toole/skindeep#22]
Categories such as 'Back To Basics' have a banner image that displays the category title.
The category title is also shown as text by the theme.
The redundant title text should be removed.
This includes product categories.

**Comment by jerome-toole** [comment]
yo briggy, have you considered SEO and accessibility on this? Those pages need the category name in the `<title>` tag, and a header (probably `h1`) of the category name. If you took the header away, I recommend you bring it back and add a css class as follows:

```css
.visuallyhidden { 
  position: absolute; 
  overflow: hidden; 
  clip: rect(0 0 0 0); 
  height: 1px; width: 1px; 
  margin: -1px; padding: 0; border: 0; 
}
```

Hidden but not from screen readers or search engines.
